### ISSUE TITLE
virtually-geometric  兄弟。

### ISSUE THREAD

**Issue by fzw2408** [AIFanatic/three-nanite#1]
1真心崇拜一下。 要是wiki完善些【how to build wasm】。或许会有更多人加入。
 2很遗憾的下面的两个大佬没有开源，嘿嘿，我是顺着网线找到这个你这个GitHub。is a great work！！！！
https://discourse.threejs.org/t/virtually-geometric/28420
https://zhuanlan.zhihu.com/p/556616601?utm_id=0

**Comment by AIFanatic** [comment]
Thanks, the project is quite a mess at the moment but depending on how this goes im planning on documenting everything.
I agree that its a shame that no implementations of virtual geometry are open source that's part of the reason for this repo. The whole thing seems relatively straightforward but the devil is in the details.

Regarding the wasm compilations get emsdk, activate the emsdk environment and run "three-nanite/src/metis-js/metis-5.1.0/em-build.sh" and "src/meshoptimizer/js-build.sh".
Note that some paths will need to be updated inside the scripts.
